
local _addonName, _addon = ...;

_addon.PoI = {
["zones"] = {
-- Kalimdor
	--{["id"] = 43	,["continent"] = "Kalimdor"	,["name"] = "Ashenvale"}
	-- ,{["id"] = 181	,["continent"] = "Kalimdor"	,["name"] = "Azshara"}
	{["id"] = 464	,["continent"] = "Kalimdor"	,["name"] = "Azuremyst Isle"	,["pointIds"] = {120}}
	-- ,{["id"] = 476	,["continent"] = "Kalimdor"	,["name"] = "Bloodmyst Isle"}
	-- ,{["id"] = 42	,["continent"] = "Kalimdor"	,["name"] = "Darkshore"}
	,{["id"] = 381	,["continent"] = "Kalimdor"	,["name"] = "Darnassus"			,["pointIds"] = {30, 31, 32, 33}}
	-- ,{["id"] = 101	,["continent"] = "Kalimdor"	,["name"] = "Desolace"}
	-- ,{["id"] = 4	,["continent"] = "Kalimdor"	,["name"] = "Durotar"}
	-- ,{["id"] = 141	,["continent"] = "Kalimdor"	,["name"] = "Dustwallow Marsh"}
	-- ,{["id"] = 182	,["continent"] = "Kalimdor"	,["name"] = "Felwood"}
	-- ,{["id"] = 121	,["continent"] = "Kalimdor"	,["name"] = "Feralas"}
	-- ,{["id"] = 795	,["continent"] = "Kalimdor"	,["name"] = "Molten Front"}
	-- ,{["id"] = 241	,["continent"] = "Kalimdor"	,["name"] = "Moonglade"}
	-- ,{["id"] = 606	,["continent"] = "Kalimdor"	,["name"] = "Mount Hyjal"}
	-- ,{["id"] = 9	,["continent"] = "Kalimdor"	,["name"] = "Mulgore"}
	-- ,{["id"] = 11	,["continent"] = "Kalimdor"	,["name"] = "Northern Barrens"}
	,{["id"] = 321	,["continent"] = "Kalimdor"	,["name"] = "Orgrimmar"			,["pointIds"] = {40, 41, 42, 43, 44, 45, 46, 47, 48, 49}}
	-- ,{["id"] = 261	,["continent"] = "Kalimdor"	,["name"] = "Silithus"}
	-- ,{["id"] = 607	,["continent"] = "Kalimdor"	,["name"] = "Southern Barrens"}
	-- ,{["id"] = 81	,["continent"] = "Kalimdor"	,["name"] = "Stonetalon Mountains"}
	-- ,{["id"] = 161	,["continent"] = "Kalimdor"	,["name"] = "Tanaris"}
	,{["id"] = 41	,["continent"] = "Kalimdor"	,["name"] = "Teldrassil"		,["pointIds"] = {114, 115, 116, 117, 118, 119}}
	,{["id"] = 471	,["continent"] = "Kalimdor"		,["name"] = "The Exodar"	,["pointIds"] = {35, 36, 37, 38}}
	-- ,{["id"] = 61	,["continent"] = "Kalimdor"	,["name"] = "Thousand Needles"}
	,{["id"] = 362	,["continent"] = "Kalimdor"	,["name"] = "Thunder Bluff"		,["pointIds"] = {50, 51, 52, 53, 54, 55, 56}}
	-- ,{["id"] = 720	,["continent"] = "Kalimdor"	,["name"] = "Uldum"}
	-- ,{["id"] = 201	,["continent"] = "Kalimdor"	,["name"] = "Un'Goro Crater"}
	-- ,{["id"] = 281	,["continent"] = "Kalimdor"	,["name"] = "Winterspring"}
	
	-- Eastern Kingdoms
	-- ,{["id"] = 614	,["continent"] = "Eastern Kingdoms"	,["name"] = "Abyssal Depths"	,["pointIds"] = {}}
	-- ,{["id"] = 16	,["continent"] = "Eastern Kingdoms"	,["name"] = "Arathi Highlands"}
	-- ,{["id"] = 17	,["continent"] = "Eastern Kingdoms"	,["name"] = "Badlands"}
	-- ,{["id"] = 19	,["continent"] = "Eastern Kingdoms"	,["name"] = "Blasted Lands"}
	-- ,{["id"] = 29	,["continent"] = "Eastern Kingdoms"	,["name"] = "Burning Steppes"}
	-- ,{["id"] = 32	,["continent"] = "Eastern Kingdoms"	,["name"] = "Deadwind Pass"}
	,{["id"] = 27	,["continent"] = "Eastern Kingdoms"	,["name"] = "Dun Morogh"		,["pointIds"] = {107, 108, 109, 110, 111, 112, 113}}
	-- ,{["id"] = 34	,["continent"] = "Eastern Kingdoms"	,["name"] = "Duskwood"}
	-- ,{["id"] = 23	,["continent"] = "Eastern Kingdoms"	,["name"] = "Eastern Plaguelands"}
	,{["id"] = 30	,["continent"] = "Eastern Kingdoms"	,["name"] = "Elwynn Forest"		,["pointIds"] = {91, 92, 92, 93, 94, 95, 96, 97, 98, 99}}
	,{["id"] = 462	,["continent"] = "Eastern Kingdoms"	,["name"] = "Eversong Woods"	,["pointIds"] = {80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90}}
	-- ,{["id"] = 463	,["continent"] = "Eastern Kingdoms"	,["name"] = "Ghostlands"}
	-- ,{["id"] = 545	,["continent"] = "Eastern Kingdoms"	,["name"] = "Gilneas"}
	-- ,{["id"] = 611	,["continent"] = "Eastern Kingdoms"	,["name"] = "Gilneas City"}
	-- ,{["id"] = 24	,["continent"] = "Eastern Kingdoms"	,["name"] = "Hillsbrad Foothills"}
	,{["id"] = 341	,["continent"] = "Eastern Kingdoms"	,["name"] = "Ironforge"			,["pointIds"] = {20, 21, 22, 23, 24, 25, 26 ,27 ,28 ,29}}
	-- ,{["id"] = 499	,["continent"] = "Eastern Kingdoms"	,["name"] = "Isle of Quel'Danas"}
	-- ,{["id"] = 610	,["continent"] = "Eastern Kingdoms"	,["name"] = "Kelp'thar Forest"}
	-- ,{["id"] = 35	,["continent"] = "Eastern Kingdoms"	,["name"] = "Loch Modan"}
	-- ,{["id"] = 37	,["continent"] = "Eastern Kingdoms"	,["name"] = "Northern Stranglethorn"}
	-- ,{["id"] = 36	,["continent"] = "Eastern Kingdoms"	,["name"] = "Redridge Mountains"}
	-- ,{["id"] = 684	,["continent"] = "Eastern Kingdoms"	,["name"] = "Ruins of Gilneas"}
	-- ,{["id"] = 685	,["continent"] = "Eastern Kingdoms"	,["name"] = "Ruins of Gilneas City"}
	-- ,{["id"] = 28	,["continent"] = "Eastern Kingdoms"	,["name"] = "Searing Gorge"}
	-- ,{["id"] = 615	,["continent"] = "Eastern Kingdoms"	,["name"] = "Shimmering Expanse"}
	,{["id"] = 480	,["continent"] = "Eastern Kingdoms"	,["name"] = "Silvermoon City"	,["pointIds"] = {70,71, 72, 73, 74, 75, 76}}
	-- ,{["id"] = 21	,["continent"] = "Eastern Kingdoms"	,["name"] = "Silverpine Forest"}
	,{["id"] = 301	,["continent"] = "Eastern Kingdoms"	,["name"] = "Stormwind City"	,["pointIds"] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11}}
	-- ,{["id"] = 38	,["continent"] = "Eastern Kingdoms"	,["name"] = "Swamp of Sorrows"}
	-- ,{["id"] = 673	,["continent"] = "Eastern Kingdoms"	,["name"] = "The Cape of Stranglethorn"}
	-- ,{["id"] = 26	,["continent"] = "Eastern Kingdoms"	,["name"] = "The Hinterlands"}
	-- ,{["id"] = 502	,["continent"] = "Eastern Kingdoms"	,["name"] = "The Scarlet Enclave"}
	-- ,{["id"] = 20	,["continent"] = "Eastern Kingdoms"	,["name"] = "Tirisfal Glades"}
	-- ,{["id"] = 708	,["continent"] = "Eastern Kingdoms"	,["name"] = "Tol Barad"}
	-- ,{["id"] = 709	,["continent"] = "Eastern Kingdoms"	,["name"] = "Tol Barad Peninsula"}
	-- ,{["id"] = 700	,["continent"] = "Eastern Kingdoms"	,["name"] = "Twilight Highlands"}
	,{["id"] = 382	,["continent"] = "Eastern Kingdoms"	,["name"] = "Undercity"			,["pointIds"] = {60, 61, 62, 63, 64, 65, 66, 67}}
	-- ,{["id"] = 613	,["continent"] = "Eastern Kingdoms"	,["name"] = "Vashj'ir"}
	-- ,{["id"] = 22	,["continent"] = "Eastern Kingdoms"	,["name"] = "Western Plaguelands"}
	,{["id"] = 39	,["continent"] = "Eastern Kingdoms"	,["name"] = "Westfall"			,["pointIds"] = {100, 101, 102, 103, 104, 105, 106}}
	-- ,{["id"] = 40	,["continent"] = "Eastern Kingdoms"	,["name"] = "Wetlands"}
	
	-- Outland
	-- ,{["id"] = 466	,["continent"] = "Outland"	,["name"] = "Outland"}
	-- ,{["id"] = 475	,["continent"] = "Outland"	,["name"] = "Blade's Edge Mountains"}
	-- ,{["id"] = 465	,["continent"] = "Outland"	,["name"] = "Hellfire Peninsula"}
	-- ,{["id"] = 477	,["continent"] = "Outland"	,["name"] = "Nagrand"}
	-- ,{["id"] = 479	,["continent"] = "Outland"	,["name"] = "Netherstorm"}
	-- ,{["id"] = 473	,["continent"] = "Outland"	,["name"] = "Shadowmoon Valley"}
	-- ,{["id"] = 481	,["continent"] = "Outland"	,["name"] = "Shattrath City"}
	-- ,{["id"] = 478	,["continent"] = "Outland"	,["name"] = "Terokkar Forest"}
	-- ,{["id"] = 467	,["continent"] = "Outland"	,["name"] = "Zangarmarsh"}
	
	-- Northrend
	-- ,{["id"] = 485	,["continent"] = "Northrend"	,["name"] = "Northrend"}
	-- ,{["id"] = 486	,["continent"] = "Northrend"	,["name"] = "Borean Tundra"}
	-- ,{["id"] = 510	,["continent"] = "Northrend"	,["name"] = "Crystalsong Forest"}
	-- ,{["id"] = 504	,["continent"] = "Northrend"	,["name"] = "Dalaran"}
	-- ,{["id"] = 488	,["continent"] = "Northrend"	,["name"] = "Dragonblight"}
	-- ,{["id"] = 490	,["continent"] = "Northrend"	,["name"] = "Grizzly Hills"}
	-- ,{["id"] = 491	,["continent"] = "Northrend"	,["name"] = "Howling Fjord"}
	-- ,{["id"] = 541	,["continent"] = "Northrend"	,["name"] = "Hrothgar's Landing"}
	-- ,{["id"] = 492	,["continent"] = "Northrend"	,["name"] = "Icecrown"}
	-- ,{["id"] = 493	,["continent"] = "Northrend"	,["name"] = "Sholazar Basin"}
	-- ,{["id"] = 495	,["continent"] = "Northrend"	,["name"] = "The Storm Peaks"}
	-- ,{["id"] = 501	,["continent"] = "Northrend"	,["name"] = "Wintergrasp"}
	-- ,{["id"] = 496	,["continent"] = "Northrend"	,["name"] = "Zul'Drak"}
	
	-- Pandaria
	-- ,{["id"] = 862	,["continent"] = "Pandaria"	,["name"] = "Pandaria"}
	-- ,{["id"] = 858	,["continent"] = "Pandaria"	,["name"] = "Dread Wastes"}
	-- ,{["id"] = 929	,["continent"] = "Pandaria"	,["name"] = "Isle of Giants"}
	-- ,{["id"] = 928	,["continent"] = "Pandaria"	,["name"] = "Isle of Thunder"}
	-- ,{["id"] = 857	,["continent"] = "Pandaria"	,["name"] = "Krasarang Wilds"}
	-- ,{["id"] = 809	,["continent"] = "Pandaria"	,["name"] = "Kun-Lai Summit"}
	-- ,{["id"] = 905	,["continent"] = "Pandaria"	,["name"] = "Shrine of Seven Stars"}
	-- ,{["id"] = 903	,["continent"] = "Pandaria"	,["name"] = "Shrine of Two Moons"}
	-- ,{["id"] = 806	,["continent"] = "Pandaria"	,["name"] = "The Jade Forest"}
	-- ,{["id"] = 873	,["continent"] = "Pandaria"	,["name"] = "The Veiled Stair"}
	-- ,{["id"] = 808	,["continent"] = "Pandaria"	,["name"] = "The Wandering Isle"}
	-- ,{["id"] = 951	,["continent"] = "Pandaria"	,["name"] = "Timeless Isle"}
	-- ,{["id"] = 810	,["continent"] = "Pandaria"	,["name"] = "Townlong Steppes"}
	-- ,{["id"] = 811	,["continent"] = "Pandaria"	,["name"] = "Vale of Eternal Blossoms"}
	-- ,{["id"] = 807	,["continent"] = "Pandaria"	,["name"] = "Valley of the Four Winds"}
	
	-- Draenor
	-- ,{["id"] = 962	,["continent"] = "Draenor"	,["name"] = "Draenor"}
	-- ,{["id"] = 978	,["continent"] = "Draenor"	,["name"] = "Ashran"}
	-- ,{["id"] = 941	,["continent"] = "Draenor"	,["name"] = "Frostfire Ridge"}
	-- ,{["id"] = 949	,["continent"] = "Draenor"	,["name"] = "Gorgrond"}
	-- ,{["id"] = 950	,["continent"] = "Draenor"	,["name"] = "Nagrand"}
	-- ,{["id"] = 947	,["continent"] = "Draenor"	,["name"] = "Shadowmoon Valley"}
	-- ,{["id"] = 948	,["continent"] = "Draenor"	,["name"] = "Spires of Arak"}
	-- ,{["id"] = 1009	,["continent"] = "Draenor"	,["name"] = "Stormshield"}
	-- ,{["id"] = 946	,["continent"] = "Draenor"	,["name"] = "Talador"}
	-- ,{["id"] = 945	,["continent"] = "Draenor"	,["name"] = "Tanaan Jungle"}
}
,["points"] = {
	[1]		= 	{["title"] = "Cathedral of Light"	,["x"] = 53.16	,["y"] = 51.50	,["scale"] = 2	,["lore"] = "The Cathedral is home to some of the most powerful and influential holy leaders in the world.\nDuthorian Rall is perhaps Stormwind City's most accomplished paladin.\nThe archbishop himself also resides within the hallowed chambers."}
	,[2]	= 	{["title"] = "Stormwind Harbor"		,["x"] = 40.70	,["y"] = 47.28	,["scale"] = 2	,["lore"] = "Stormwind Harbor is one of the major ports for transport to both Northrend and Kalimdor, thereby connecting to Valiance Keep in the Borean Tundra and Rut'theran Village in Teldrassil."}
	,[3]	= 	{["title"] = "Stormwind Cemetery"	,["x"] = 45.62	,["y"] = 29.42	,["scale"] = 2	,["lore"] = "Among those buried here is Queen Tiffin Wrynn, wife of King Varian.\nSome say you can talk to one of the deceased, if you can find his grave."}
	,[4]	= 	{["title"] = "Deeprum Tram"			,["x"] = 67.69	,["y"] = 33.39	,["scale"] = 2	,["lore"] = "King Bronzebeard turned to Azeroth's most esteemed engineer, High Tinker Gelbin Mekkatorque, who immediately began drafting designs for a grand subterranean railway system that would link Stormwind and Ironforge.\nHis vision has become reality, and the newly-built Deeprun Tram has developed into an indispensable link between the two great capitals, providing swift and safe transportation for thousands of their citizens, and bolstering military cooperation between the armies of these two proud Alliance strongholds.\n\nShortly after the petrification of Magni, Moira invaded Ironforge and closed the tram, isolating the dwarves in the city. Some time later, Varian led an elite strike team of SI:7 agents through the tram into Ironforge."}
	,[5]	= 	{["title"] = "Stormwind Keep"		,["x"] = 84.99	,["y"] = 32.71	,["scale"] = 2	,["lore"] = "The mighty Stormwind Keep is the seat of power of the human kingdom of Stormwind.\nThe residence of King Varian Wrynn and his son Anduin, the keep also houses the extensive Royal Library where nobles and scholars from across the known world research various topics."}
	,[6]	= 	{["title"] = "Stormwind Park"		,["x"] = 44.84	,["y"] = 69.57	,["scale"] = 2	,["lore"] = "The Park used to be the district located in the western corner of Stormwind City. It was once a district devoted to leisure activities for Stormwind's populace until it became a refuge for visiting night elves, who found the comforting presence of nature a welcome respite from the vast stone thoroughfares of Stormwind proper. It was the only place in the Eastern Kingdoms where druid trainers resided. The night elves created a Moonwell in the center of the park square.\n\nThe Park was destroyed by Deathwing's visit to Stormwind, during the Shattering. When he attacked the city, the druid trainer Sheldras Moontree, priest trainer Nara Meideros, and Argos Nightwhisper were the only ones known to escape alive, with the rest unaccounted for. They have relocated down to Stormwind Harbor. All that remains of the Park are the ruins of The Old Barracks."}
	,[7]	= 	{["title"] = "Wizard's Sanctum"		,["x"] = 49.86	,["y"] = 87.78	,["scale"] = 2	,["lore"] = "The Wizard's Sanctum, or Academy of Arcane Sciences, is a vine-covered tower that sits to the west of Stormwind City. For a long time, the Academy was considered to be a second-best school of magic compared to Dalaran, but since that region's destruction by the demons and undead, the northern mages fled to Stormwind and took up residence in the tower. It's full to bursting with mages, and some say it's difficult to get a word in edgeways with the differing opinions inside. Yet as it's the only magic school left in the east, few complain openly.\n\nSeemingly led by Maginor Dumas, the magi here strive to decipher arcane mysteries and uncover eldritch lore. Larimaine Purdue, the resident portalmancer, has created a rift portal deep in the Sanctum. She keeps the portal under close guard, and for now, will not let anyone venture through its swirling vortex. It is unknown where it leads to.\n\nThe Sanctum houses Stormwind wizards' guild, the Academy of the Arcane Sciences, and is currently one of the foremost centers of human arcane research and study today. Many high elves also seek refuge in the arcane halls, quenching their addiction and thirst for power in a safe environment."}
	,[8]	= 	{["title"] = "SI:7"					,["x"] = 80.72	,["y"] = 61.29	,["scale"] = 2	,["lore"] = "SI:7, which stands for Stormwind Intelligence, is a secretive branch of King Varian's forces. It includes rogues specializing in special operations, espionage, assassination and stealth tactics.\n\nThe organization is currently led by Master Mathias Shaw. They have operatives all throughout the Eastern Kingdoms who carry out secret missions for Stormwind, such as Renzik \"The Shiv\" and Flint Shadowmore. They also have some operatives in the Kalimdor region, such as Andello Porter.\n\nThe black stallion is rumored to be favored by the SI:7 for night missions due to its dark coat."}
	,[9]	= 	{["title"] = "Eastern Earthshrine"	,["x"] = 74.38	,["y"] = 18.42	,["scale"] = 2	,["lore"] = "The Eastern Earthshrine is a ritual circle erected by the Earthen Ring for use by the Alliance.\nThe Earthshrine provides portals to Mount Hyjal, Vashj'ir, Deepholm, Uldum, Twilight Highlands and Tol Barad."}
	,[10]	= {["title"] = "Valley of Heroes"		,["x"] = 70.73	,["y"] = 85.77	,["lore"] = "The Valley of Heroes is a valley that lies before Stormwind Gate. A bridge of stone crosses the narrow moat and is the first sight of all who enter. \n\nStatues of Alliance heroes stand on either side of the road, welcoming visitors while providing an awe-inspiring warning. These heroes comprised the Alliance Expedition that travelled through the Dark Portal into Draenor to seal the dimensional rift from that side.\nOn the left are Kurdran Wildhammer, Thane of Aerie Peak, and the Archmage Khadgar of the Kirin Tor; on the right are Force Commander Danath Trollbane and Ranger-Captain Alleria Windrunner; at the end of the main road, just before it splits to enter Stormwind City proper, is General Turalyon, the expedition's military leader."}
	,[11]	= {["title"] = "Stormwind Stockade"		,["x"] = 51.50	,["y"] = 68.31	,["lore"] = "Stormwind Stockade is a high-security prison complex, hidden beneath the canal district of Stormwind City.\nPresided over by Warden Thelwater, the Stockade is home to petty crooks, political insurgents, murderers and a score of the most dangerous criminals in the land.\n\nA large number of dangerous criminals, including some criminal masterminds and Defias mercenaries, are currently being held in the stockade.\nHowever, not so long ago, there was a revolt inside the dungeon, and the prisoners now keep the Stockade under their control."}
	
	,[20]	= {["title"] = "Deeprum Tram"			,["x"] = 75.82	,["y"] = 51.00	,["lore"] = "King Bronzebeard turned to Azeroth's most esteemed engineer, High Tinker Gelbin Mekkatorque, who immediately began drafting designs for a grand subterranean railway system that would link Stormwind and Ironforge.\nHis vision has become reality, and the newly-built Deeprun Tram has developed into an indispensable link between the two great capitals, providing swift and safe transportation for thousands of their citizens, and bolstering military cooperation between the armies of these two proud Alliance strongholds.\n\nShortly after the petrification of Magni, Moira invaded Ironforge and closed the tram, isolating the dwarves in the city. Some time later, Varian led an elite strike team of SI:7 agents through the tram into Ironforge."}
	,[21]	= {["title"] = "Tinker Town"			,["x"] = 70.63	,["y"] = 49.45	,["scale"] = 2	,["lore"] = "Originally, Tinker Town was just a small quarter of the city for gnomes visiting from Gnomeregan to use.\nWhen their clockwork city of Gnomeregan fell, it became the center of the gnomish court in exile (the Gnomeregan Exiles).\nPrior to the partial retaking of Gnomeregan, High Tinker Mekkatorque could be found here, along with his closest advisers."}
	,[22]	= {["title"] = "Hall of Explorers"		,["x"] = 68.33	,["y"] = 20.06	,["scale"] = 2	,["lore"] = "The Hall of Explorers is home to the famed Ironforge Explorers' Guild (aka Explorer's League).\nEvery archaeological expedition the Alliance sends out is coordinated from here.\nIt also houses the the Library which houses a museum ran by Curator Thorius."}
	,[23]	= {["title"] = "Forlorn Cavern"			,["x"] = 47.47	,["y"] = 12.13	,["scale"] = 2	,["lore"] = "The Forlorn Cavern is a long, winding road built around Ironforge's underground lake.\nIt's naturally dark and secluded nature makes it perfect for lots of shady deals."}
	,[24]	= {["title"] = "Mystic Ward"			,["x"] = 28.73	,["y"] = 14.36	,["scale"] = 2	,["lore"] = "The Mystic Ward was established for the study of magic.\nThe Hall of Mysteries houses powerful magic users and is the center of arcane and divine power in the dwarven kingdom."}
	,[25]	= {["title"] = "Commons"				,["x"] = 30.68	,["y"] = 66.70	,["scale"] = 2	,["lore"] = "The area known as the Commons is the main thoroughfare for trade in the city of Ironforge.\nIt contains the bank, Auction House and inn, as well as a few shops.\nThe Commons is always the busiest and most crowded portion of the city."}
	,[26]	= {["title"] = "Military Ward"			,["x"] = 64.43	,["y"] = 79.04	,["scale"] = 2	,["lore"] = "The Military Ward serves as the command center for the Ironforge Military, as well as a center for all things martial.\nThe Hall of Arms is the center of dwarven military power and a hangar for both steam tanks and dwarven flying machines."}
	,[27]	= {["title"] = "Great Forge"			,["x"] = 50.56	,["y"] = 42.70	,["scale"] = 2	,["lore"] = "The Great Forge is the heart and soul of dwarven culture, where all of their ingenious creations and weapons are made.\nIt was here, upon the The Great Anvil itself, that the legendary blade Ashbringer was forged by King Magni."}
	,[28]	= {["title"] = "High Seat"				,["x"] = 40.74	,["y"] = 54.12	,["lore"] = "The High Seat is the former throne room of King Magni Bronzebeard in the dwarf city of Ironforge.\nAfter Magni Bronzebeard was turned to diamond, the leadership of Ironforge was assumed by the Council of Three Hammers: his daughter Moira Thaurissan, his brother Muradin Bronzebeard, and Falstad Wildhammer."}
	,[29]	= {["title"] = "Old Ironforge"			,["x"] = 44.28	,["y"] = 51.96	,["lore"] = "After Magni Bronzebeard received earthen-related stone tablets from Brann in an attempt to learn about the pre-Cataclysm disturbances, Magni ordered the sealed gates of Old Ironforge to be opened for a ritual.\nThe key took two dwarves to lift, and it took a ladder for them to reach the lock.\nAfter venturing through the door, a linear path led Anduin, Muninn Magellas, Advisor Belgrum, High Priest Rohan and Reyna Stonebranch to a large cavern.\nA surprisingly new-looking carpeted path led upwards to a broad platform capable of holding a large group, and an unadorned stone path led downwards.\nWith an incantation scroll and a potion, Magni performed the ritual.\nWhile listening to the incantation, Anduin called this place the \"heart of the earth\".\nThe ritual seemingly worked, but turned him into a solid diamond statue."}
	,[30]	= {["title"] = "Bough of the Eternal"	,["x"] = 44.77	,["y"] = 51.84	,["lore"] = "The Bough of the Eternals is a tree in the Temple Gardens of Darnassus where the city's bank can be found within.\nIt is tree that grew into the shape of a bear with a bird on its back, the two basic druid animal forms.\nThe bear is also likely either Ursoc or Ursol, two of the Eternals that fought and died during the War of the Ancients."}
	,[31]	= {["title"] = "Temple of the Moon"		,["x"] = 43.00	,["y"] = 76.21	,["lore"] = "The Temple of the Moon in Darnassus is the dwelling of the Sisters of Elune, and the center of all night elf spiritual life.\nIt is said that Elune herself resides here in spirit.\nIt's waters are blessed and described as the water of Elune.\n\nTyrande Whisperwind, the religious leader of the night elves, can be found on the second level.\n\nThe iconic statue at the center of the Temple depicts Haidene, the first High Priestess of the Moon."}
	,[32]	= {["title"] = "Cenarion Enclave"		,["x"] = 41.57	,["y"] = 32.38	,["lore"] = "The Cenarion Enclave is a magical place which the druids of Darnassus call home.\nArchdruid Fandral Staghelm formerly led his followers and kin from the boughs of the Enclave, until Malfurion returned from the Emerald Dream."}
	,[33]	= {["title"] = "Howling Oak"			,["x"] = 48.86	,["y"] = 18.00	,["lore"] = "The Howling Oak, located in the night elf capital of Darnassus, is the new home of the Gilnean refugees after the fall of Gilneas.\nIt is dominated by a \"worgen tree\" very similar to Tal'doren in the Blackwald.\n\nThe tree, as its name implies, is an actual oak tree.\nIt was grown through the aid of the night elf druids from a seed taken from Gilneas.\nIt stands for all the Gilneans have endured, and all that their people accomplished."}
		
	,[35]	= {["title"] = "Vault of Lights"		,["x"] = 33.64	,["y"] = 66.34	,["lore"] = "The Vault of Lights is the favorite haunt of the Prophet Velen.\n\nThe Vault is notable for its central area, which looks like a set of purple holograms of various mobs.\nIt is in fact a museum or tactical information data bank of several Burning Legion units.\nOccasionally a draenei tour group strides from one hologram to another.\nAs these group approaches various hologram emitters, the emitters state facts about the particular unit, namely the name, the species, its affiliation, and its function."}
	,[36]	= {["title"] = "Crystal Hall"			,["x"] = 38.28	,["y"] = 28.38	,["lore"] = "The Crystal Hall is an area of the Exodar.\nThe shaman trainers can be found here, as well as a small crystal-digging mine full of Broken workers.\nNote that the shamans are not all draenei; there are also furbolg and broken shaman around, including the most important one, Farseer Nobundo, located at the small elevated platform in the zone.\n\nAn interesting fact is that the draenei harvest crystals in the northern portion of the hall, where Broken draenei miners use their mining picks to gather the precious gems.\nThe crystals are used to repair the Exodar.\nThe Broken draenei, though still draenei in some regard, seem treated like a lesser class; a labor and task force.\nIt is kind of odd that a race with such an attachment to the Light treats those who were once their own people with such distaste.\nIt is possible that the arrangment was agreed to by the Broken draenei; their bodies better suited to manual labor than the \"pure\" draenei."}
	,[37]	= {["title"] = "Trader's Tier"			,["x"] = 58.61	,["y"] = 70.21	,["lore"] = "As the name implies, the Trader's Tier is where most of trade in Exodar takes place"}
	,[38]	= {["title"] = "Seat of the Naaru"		,["x"] = 54.73	,["y"] = 49.05	,["lore"] = "The Seat of the Naaru is the central section of the Exodar where O'ros, a naaru, resides down on the lower levels.\nO'ros is the last naaru in the line of Xe'ra, the naaru prime."}
	,[40]	= {["title"] = "Ragefire Chasm"			,["x"] = 65.95	,["y"] = 50.70	,["level"] = 2 	,["scale"] = 5	,["lore"] = "Beneath the city of Orgrimmar lies this fiery chasm.\nA clan of troggs known as Ragefire Troggs had begun to appear in the chasm, from deep below the lava-filled tunnels.\nMagatha the Seer, of the tauren people, attempted to make peace with these creatures, but was met only with hostility.\nIt was clear that these troggs were not interested in diplomacy, and could potentially overwhelm the entire Horde if left unchecked.\n\nA sect of the mysterious Shadow Council had also taken refuge in this chasm.\nThis sect is known as the Searing Blade, and was led by Taragaman the Hungerer, a felguard; Jergosh the Invoker, a powerful warlock; and Bazzalan, a satyr.\nFrom their dark hiding place, they plotted to overthrow and destroy all that the Horde has built for themselves in these lands.\n\nAfter the Shattering, the Dark Shaman were formed and overtook Ragefire Chasm.\nThey cleared the presence of Searing Blade cultists and troggs, and used the latter to feed the enslaved beasts they brought from the Firelands.\nAlthough Warchief Garrosh Hellscream called on a number of shaman to use the elements as weapons against the Alliance, the chasm's inhabitants appear to be renegades.\nReports have surfaced that these shadowy figures are amassing a blistering army that could wreak havoc if unleashed upon Orgrimmar."}
	,[41]	= {["title"] = "Brawl'gar Arena"		,["x"] = 70.34	,["y"] = 31.48	,["lore"] = "In the Brawl'gar Arena creatures and fighters from all over Azeroth and Outland have been gathered to participate in bloody arena deathmatches with heroes of the Horde.\n\nThe building housing the arena is also known as the Ring of Valor, notable for being the site of a duel between Thrall and Garrosh Hellscream during the Scourge Invasion."}
	,[42]	= {["title"] = "Western Earthshrine"	,["x"] = 50.05	,["y"] = 37.84	,["lore"] = "The Western Earthshrine is a ritual circle erected by the Earthen Ring for use by the Horde.\nThe Earthshrine provides portals to Mount Hyjal, Vashj'ir, Deepholm, Uldum, Twilight Highlands and Tol Barad."}
	,[43]	= {["title"] = "Skyway"					,["x"] = 49.42	,["y"] = 58.77	,["lore"] = "Orgrimmar Skyway is the city's main connetion to places across Azeroth.\n\nIts two zeppelin towers provide access to Thunderbluff, Tirisfal Glades near Undercity, Grom'gol in Stranglethorn Jungle, Warsong Hold in Borean Tundra"}
	,[44]	= {["title"] = "Hall of Legends"		,["x"] = 40.27	,["y"] = 71.84	,["lore"] = "The Hall of Legends in Orgrimmar houses the secret armory of the Crimson Ring.\nThe weapons stored here come from every continent on Azeroth and the orcs' homeworld, Draenor.\nMany were taken as spoils of war and bear a proud history of battles lost and won."}
	,[45]	= {["title"] = "Grommash Hold"			,["x"] = 49.45	,["y"] = 74.31	,["lore"] = "Grommash Hold is an enormous fortress located in the Valley of Strength in the orc capital of Orgrimmar.\nIt is named after the orcish hero Grom Hellscream, and serves as the administrative center of the Horde.\n\nBefore going hungry for power and being overthrown, Garrosh Hellscream, previous Warchief and son of Grom, resided here.\nNow the new Warchief, Vol'jin, and his advisors reside here."}
	,[46]	= {["title"] = "Goblin Slums"			,["x"] = 40.11	,["y"] = 80.10	,["lore"] = "The Goblin Slums is the new district in Orgrimmar for the goblin refugees of Kezan.\nIt connects to the Valley of Spirits, and is an oily, dirty place - just the way the goblins like it.\n\nThe space now occupied by the Goblin Slums was part of the Valley of Spirits prior to the goblins joining the Horde.\nThe trolls moved further north in the valley, while the goblins were given this part of the valley to use as their own.\nThe slums are presided over by Boss Mida, who was added as a result of the Trade Princess Movement.\nOff-duty goblins can be found lounging around the pool area as well as waiting in line to withdraw their money from the bank, and off-duty Orgrimmar Grunts join them to converse and tell jokes.\n\nThere appears to be an oil-drilling operation within the lake, overseen by Environmental Engineer Linza; the surrounding area is filthy, with the pollution flowing downstream to the new Valley of Spirits."}
	,[47]	= {["title"] = "Valley of Spirits"		,["x"] = 33.92	,["y"] = 68.27	,["lore"] = "Many parts of this valley sunk due to the Shattering and caused the large pool of water at the southern end to flow into the rest of the valley flooding a majority of it.\nThe two huts in that pool were destroyed and the area was given to the goblins of the Bilgewater Cartel, which they now call the Goblin Slums.\n\nMost of the orcish building survived here and continue to be used by their previous residents.\nThe Darkspear trolls have since been allowed to use this valley to build and expand upon.\nA tunnel to bypass the Goblin Slums was also dug through the mountain to the Valley of Wisdom.\n\nNear the end of Garrosh's rule, the district was put under martial law by the Kor'kron under orders from Garrosh himself due to the heavy troll population.\nThis was due to the recent rebellion against Garrosh's rule.\nCurfews were put in order, and Kor'kron guards actively patroled the district and arrested all suspicious individuals.\nSince his downfall, the Valley of Spirits has returned to its normal state."}
	,[48]	= {["title"] = "Valley of Wisdom"		,["x"] = 40.76	,["y"] = 47.91	,["lore"] = "The Valley of Wisdom was once the location of Grommash Hold, where Warchief Thrall once resided in Orgrimmar.\nWhen the Cataclysm stuck much of the area changed as the land sunk in some places creating spots for pools to form.\n\nA few remains of Grommash Hold can still be seen where the tauren were allowed to setup huts and take this valley for their own use.\nThe armor of pit lord Mannoroth, which once rested on a tree here is now gone and the tree was destroyed."}
	,[49]	= {["title"] = "Valley of Honor"		,["x"] = 67.78	,["y"] = 43.41	,["lore"] = "The Valley of Honor is the location for all things having to do with warfare in Orgrimmar.\nThe Ring of Valor arena is located here.\nThe Hall of the Brave houses the warrior guild, as well as all the city's battlemasters.\n\nThe Shattering has caused the land to shift in the valley.\nThis shifting has destroyed the once secluded pool of water and form a larger lake that flows throughout the valley.\n\nThe orcs have blown through the northern section of the valley to create an entrance to Azshara."}
	,[50]	= {["title"] = "Hunter Rise"			,["x"] = 58.24	,["y"] = 78.21	,["lore"] = "Warriors and hunters travel here from all across the land to sharpen their skills and further their training. Like elves, tauren tend to prefer bows and other simple weapons to rifles."}
	,[51]	= {["title"] = "Elder Rise"				,["x"] = 71.74	,["y"] = 30.25	,["lore"] = "Elder Rise holds the governing Council of Elders and also members of the Cenarion Circle."}
	,[52]	= {["title"] = "Lower Rise"				,["x"] = 43.18	,["y"] = 57.17	,["lore"] = "The Lower Rise is Thunder Bluff's main hub of trade."}
	,[53]	= {["title"] = "Middle Rise"			,["x"] = 46.81	,["y"] = 39.48	,["lore"] = "The Middle Rise is Thunder Bluff's tradeskill area."}
	,[54]	= {["title"] = "High Rise"				,["x"] = 56.04	,["y"] = 51.45	,["lore"] = "The High Rise is the seat of Thunder Bluff's rule, and contains the grand tepee of Grand Chief Baine Bloodhoof.\nIt also serves as a gathering spot for tribal matters.\n\nThe new Chief of the Bloodhoof clan, Baine Bloodhoof has become the High Chieftain of the tauren race in wake of his father's death.\nHe watches over Thunder Bluff, and over his people in an ever-darkening world."}
	,[55]	= {["title"] = "Spirit Rise"			,["x"] = 27.34	,["y"] = 23.12	,["lore"] = "Spirit Rise is the center for shamanistic studies in Thunder Bluff.\nThe Skychaser tribe holds great influence here.\nBelow the surface of the mesa are the steamy Pools of Vision.\n\nThe zeppelin dock connects Thunder Bluff to Orgrimmar."}
	,[56]	= {["title"] = "Pools of Vision"		,["x"] = 30.30	,["y"] = 30.02	,["lore"] = "The Pools of Vision were mysteriously being haunted by a powerful Earth Elemental.\nCairne Bloodhoof was hesitant to drive it away because he wanted to understand what has disturbed it first, so as to discover what has disturbed the natural balance of Azeroth.\nThe gladiator champion named Lo'Gosh was able to defeat it and cleanse the Pools of Vision.\nMagatha Grimtotem glorified Lo'Gosh's victory in order to discredit Cairne for being unable to cleanse the elemental from the Pools of Vision.\nSome time later the pools were used by Stasia Fallshadow."}
	,[60]	= {["title"] = "King Terenas' tomb"		,["x"] = 65.97	,["y"] = 44.05	,["lore"] = "A memorial to king Terenas Menethil II, who was killed by his own son Arthas Menethil.\nAlthough the memorial appears to be a stone tomb, it was shown that after his death, Terenas was cremated.\nFurthermore, the urn containing his ashes was used to resurrect the Lich Kel'Thuzad.\nIt is unknown what happened to the King's remains after this point.\n\nThe memorial was crafted by the Alliance humans who once inhabited the old city, who risked everything to ensure that the memory of Lordaeron's last true king would not be forgotten."}
	,[61]	= {["title"] = "Royal Quarter"			,["x"] = 56.94	,["y"] = 91.23	,["lore"] = "The Royal Quarter of the Undercity contains the throne room where the Dark Lady Sylvanas Windrunner controls her burgeoning empire of undeath.\nBragor Bloodfist has been assigned to this area to keep tabs on the Dark Lady and report all activity to the Warchief.\n\nThe Dreadlord Varimathras was found here alongside the Dark Lady prior to the Battle for the Undercity, where he tried to overthrow her by controlling a substantial part of the Forsaken faction.\nHe was eventually faced and defeated by Thrall and Sylvanas."}
	,[62]	= {["title"] = "Apothecarium"			,["x"] = 53.28	,["y"] = 74.68	,["lore"] = "The Apothecarium is the home of the Royal Apothecary Society, a large-scale organization of undead dedicated to eradicating the \"taint of humanity\" from Lordaeron.\nThis is where the Forsaken work to brew their newest plagues, as well as creating more powerful abominations to serve in their armies.\nThis area is the domain of Master Apothecary Faranell and his alchemist minions.\n\nDuring the Battle of Undercity, the Alliance led by Varian Wrynn entered the Apothecarium and killed Putress here.\nThe king was horrified when he saw the laboratory."}
	,[63]	= {["title"] = "Rogues' Quarter"		,["x"] = 81.38	,["y"] = 67.46	,["lore"] = "The Rogues' Quarter is home to many of the Forsaken's more shady characters and the rogues' guild."}
	,[64]	= {["title"] = "Magic Quarter"			,["x"] = 81.04	,["y"] = 21.85	,["lore"] = "Magic Quarter is where the most arcane-inclined of the Forsaken come to research, learn new spells, and practice their arts, under the watchful eye of Bethor Iceshard."}
	,[65]	= {["title"] = "War Quarter"			,["x"] = 51.96	,["y"] = 23.15	,["lore"] = "The War Quarter is where the Forsaken military is based.\nHere forsaken improve their combat skills on both dead and living opponents."}
	,[66]	= {["title"] = "Sewers"					,["x"] = 45.38	,["y"] = 43.82	,["lore"] = "The Sewers are another way in and out of the city, which is guarded by abominations.\nThe tunnels allow flightpaths to leave and enter the city."}
	,[67]	= {["title"] = "Trade Quarter"			,["x"] = 68.60	,["y"] = 48.03	,["lore"] = "As the name implies, the Trade Quarter is the central hub of trade of the Undercity."}
	,[70]	= {["title"] = "Sunfury Spire"			,["x"] = 55.66	,["y"] = 22.38	,["lore"] = "Sunfury Spire is Silvermoon City's palace.\nIt is here that Regent Lord Lor'themar Theron, ruler of Quel'Thalas, governs the country with the advice and counsel of Ranger General Halduron Brightwing and Grand Magister Rommath."}
	,[71]	= {["title"] = "Hall of Blood"			,["x"] = 89.78	,["y"] = 37.49	,["lore"] = "The Hall of Blood is the headquarters of the Blood Knights, an order of blood elf paladins serving as the backbone of the Thalassian army.\n\nWith the strong support of the Magisters and the blood elven guard force, the former of which had a hand in their creation, the Blood Knights rose from unproven and scorned beginnings to become a popular group within sin'dorei society.\nThey are led by their matriarch, Lady Liadrin, who was the first of their order."}
	,[72]	= {["title"] = "Reliquary"				,["x"] = 81.33	,["y"] = 63.88	,["lore"] = "The Reliquary is the headquarters of the blood elf organization zith the same name.\nThe Reliquary is a blood elven organization dedicated to the acquisition of powerful magical artifacts and studying the past, serving as the Horde counterpart to the Explorer's League.\n\nThe leader of the Reliquary, Tae'thelan Bloodwatcher, had spent a lifetime mastering the arts of sorcery and furthering his pursuit of magical knowledge.\nGathering like-minded blood elves, he formed the Reliquary, a primarily blood elven (but nonetheless multiracial) organization to acquire powerful magical artifacts for the sin'dorei and their Horde allies.\nTae'thelan maintains that such power not only should not be feared, but can be safety utilized with proper teaching, a creed he aims to instill in allies of the Reliquary.\nThrough these moderate and controlled methods, Tae'thelan ultimately aims to free his people from their magical addiction, and unite them as the proud, mighty race they once were."}
	,[73]	= {["title"] = "Bazaar"					,["x"] = 61.18	,["y"] = 70.69	,["lore"] = "The Bazaar is Silvermoon's main hub of trade.\n\nNearby, two speakers adress the concerns af a gathering of concernd blood elves."}
	,[74]	= {["title"] = "Dead Scar"				,["x"] = 54.30	,["y"] = 56.51	,["lore"] = "A gate protects the city from the Dead Scar, a path of Blight that runs through the Kingdom of Quel'Thalas\nThe Dead Scar cuts right through Silvermoon, cutting off part of the city."}
	,[75]	= {["title"] = "The Sanctum"			,["x"] = 75.77	,["y"] = 44.03	,["lore"] = "The Sanctum is the warlock guild of Silvermoon City."}
	,[76]	= {["title"] = "Shepherd's Gate"		,["x"] = 72.40	,["y"] = 85.95	,["lore"] = "The Shepherd's Gate serves as the main entry into Silvermoon from Eversong Woods.\nThe Shepherd's Gate was not the original entrance to the city.\nRemnants of the original entry can be seen down the Dead Scar, and a large, sealed gate in the Bazaar blocks the path."}
	,[80]	= {["title"] = "Silvermoon"				,["x"] = 56.66	,["y"] = 50.24	,["scale"] = 0.5	,["lore"] = "The crown jewel of the blood elves is their capital of Silvermoon City, nestled in the Eversong Woods in their ancestral lands of Quel'Thalas.\nAt the northernmost tip of the Eastern Kingdoms the beauty of the spires and thoroughfares of Silvermoon stand in stark contrast to the Dead Scar, the tainted path that Arthas tore through the city in his quest for power.\nThough nearly destroyed by Arthas' attack on the Sunwell, Silvermoon is once again a thriving city.\n\nMost recently, the rebirth of the Sunwell has lifted spirits among the elves, and they have continued to heal Silvermoon's scars in the hopes of returning their beloved capital to its former glory."}
	,[81]	= {["title"] = "Duskwither Spire"		,["x"] = 68.92	,["y"] = 51.97	,["scale"] = 0.5	,["lore"] = "Duskwither Spire is a floating tower located in northeastern Eversong Woods.\nIt was once a magical academy run by Magister Duskwither, but fell into disrepair after the magister began looking into ill-fated ways to solve his race's addiction to magic."}
	,[82]	= {["title"] = "Dead Scar"				,["x"] = 50.34	,["y"] = 50.49	,["lore"] = "The Dead Scar is a path of Blight that runs through the Kingdom of Quel'Thalas.\nDuring the Third War, the armies of the Scourge — led by the death knight Arthas Menethil, Crown Prince of Lordaeron — marched up this path from Lordaeron all the way to the Sunwell Plateau, killing everyone and destroying everything in its path.\nThe Dead Scar practically splits Quel'Thalas in half, all the way through Silvermoon itself.\n\nToday, the Dead Scar remains in the rebuilt Quel'Thalas, as a reminder to all who live there of the horrors committed by the Scourge — and as an incentive to seek their destiny beyond the Dark Portal."}
	,[83]	= {["title"] = "Ruins of Silvermoon"	,["x"] = 45.44	,["y"] = 44.45	,["scale"] = 0.5	,["lore"] = "The area known as the Ruins of Silvermoon makes up the western half of Silvermoon City, the capital city of the blood elves and the former kingdom of Quel'Thalas.\nIt is split from the reconstructed eastern districts of Silvermoon City by the Dead Scar - the path taken by Arthas Menethil and the Scourge on their way to the Sunwell to resurrect the dead necromancer Kel'Thuzad.\n\nThe lack of energy from the Sunwell caused the high elf buildings in the Ruins of Silvermoon to fall apart."}
	,[84]	= {["title"] = "Sunsail Anchorage"		,["x"] = 32.79	,["y"] = 69.49	,["scale"] = 0.5	,["lore"] = "Sunsail Anchorage is a port located in western Eversong Woods that has been completely taken over by the Wretched.\n\nA tall, three-story building is the only structure at the Anchorage.\nIn the center of the second story is a golden orb with an arm extending through the side of the building, through a slanted opening that curves up and around the building.\nAt the end of the arm is a curled loop.\nIt can be assumed, based on the construction and location of this building as well as the shape and placement of the opening the arm extends through, that this is intended to function as a sort of cargo crane or a boat lift for maintenance or unloading."}
	,[85]	= {["title"] = "Fairbreeze Village"		,["x"] = 44.34	,["y"] = 71.1	,["lore"] = "Fairbreeze is the place where many young adventurers learn their trades, before venturing forth into Ghostlands and Tranquillien.\n\nWhen the Scourge attacked Quel'Thalas during the Third War, Sylvanas Windrunner retreated to the village and it was near here when she was killed and risen as an undead by Arthas."}
	,[86]	= {["title"] = "East Sanctum"			,["x"] = 54.24	,["y"] = 71.03	,["lore"] = "The East Sanctum is one of three arcane sanctums in Eversong Woods.\nIn ruins, it rests close to the Dead Scar.\n\nNext to the sanctum is the blood elf researcher, Apprentice Mirveda.\nShe is trying to find a way to reverse the taint on the soil of the scar, but finds that it is irreversible."}
	,[87]	= {["title"] = "Tor'Watha"				,["x"] = 69.88	,["y"] = 72.56	,["lore"] = "Tor'Watha is one of two forest troll areas of Eversong Woods. It is much larger than nearby Zeb'Watha.\nAt its eastern ridge once sat a colossal fortress of some kind with a massive set of gates.\nThe fortress was completely devoid of any inhabitants, and the forest trolls stayed in the camps below.\nIt was later deconstructed."}
	,[88]	= {["title"] = "Runestone Shan'dor"		,["x"] = 55.35	,["y"] = 84.18	,["scale"] = 0.5	,["lore"] = "Runestone Shan'dor is one of the four remaining runestones in Quel'Thalas, located at the southern edge of Eversong Woods.\nIt has become deactivated, but can be reclaimed by using the energy from an arcane crystal.\nThe runestones were placed by high elven druids or magi to mark the boundaries of their new kingdom, Quel'Thalas, when the high elves had just found it.\n\nThese enchanted monuments created a magic barrier that prevented the trolls from penetrating into Quel'Thalasand to create a magical barrier that stopped the use of arcane magic from being sensed by the Burning Legion.\nThe Runestone Shan, when reactivated, is used to protect Eversong Woods from the effects of the Plague."}
	,[89]	= {["title"] = "Runestone Falithas"		,["x"] = 44.0	,["y"] = 85.7	,["scale"] = 0.5	,["lore"] = "Runestone Falithas is one of the four remaining runestones in Quel'Thalas, located on the southern edge of Eversong Woods.\nOf the four, it is the only one to remain completely intact and functional.\nRunewarden Deryan tends to the runestone.\nThe runestones were placed by high elven druids or magi to mark the boundaries of their new kingdom, Quel'Thalas, when the high elves had just found it.\n\nThese enchanted monuments created a magic barrier that prevented the trolls from penetrating into Quel'Thalas and to create a magical barrier that stopped the use of arcane magic from being sensed by the Burning Legion.\nThe Runestone Falithas is now used to protect Eversong Woods from the effects of the Plague."}
	,[90]	= {["title"] = "Scorched Grove"			,["x"] = 37.56	,["y"] = 86.36	,["lore"] = "|Hlinktype:linkstring|hLinktext|h\nThe Scorched Grove is an area of southwestern Eversong Woods that has been completely burned down by the blood elves in an attempt to halt the Scourge forces and the spreading of the soil-tainting blight.\nSuch extreme measures were thought to be necessary, as the runestones that protected the Woods were mostly destroyed by the Scourge.\nThe Grove is now populated by several aggressive treants who defiantly try to nurture life back into the burned soil."}
	,[91]	= {["title"] = "Stormwind City"			,["x"] = 32.20	,["y"] = 49.58	,["lore"] = "Stormwind City is the capital city of the kingdom of Stormwind and the largest human city of Azeroth. After the Third War, it has become one of the last great human cities.\n\nNo city better demonstrates human determination than Stormwind. Destroyed during the Horde’s initial invasion of Azeroth, Stormwind was painstakingly reconstructed by the Stonemasons’ Guild after the Second War. Parts of the city were razed again when Deathwing, the corrupted black Dragon Aspect, brutally attacked Stormwind, but the other undamaged districts are more beautiful than ever thanks to their hardworking inhabitants. From the magnificent Cathedral of Light, which serves as a major spiritual hub, to the awe-inspiring Valley of Heroes, which commemorates the sacrifices of Stormwind’s loyal champions, the city truly represents the courageous heart of humanity."}
	,[92]	= {["title"] = "Goldshire"				,["x"] = 42.40	,["y"] = 65.67	,["lore"] = "Goldshire, along with Moonbrook, was taken in preparation of the Horde's sack of Stormwind Keep during the First Great War."}
	,[93]	= {["title"] = "Westbrook Garrison"		,["x"] = 24.42	,["y"] = 74.43	,["lore"] = "Westbrook Garrison is considered by some to be the last bastion of order heading west of Stormwind.\nThe barracks is located in Forest's Edge on the western end of Elwynn Forest near the border with Westfall.\nBeyond the garrison lie the dry fields of Westfall, currently controlled by agents of the Defias Brotherhood and their dreaded mechanical harvesters.\nSouth of the garrison the forest is full of gnolls.\nBeyond, only a river separates Elwynn Forest from shadowy Duskwood.\nThe brave defenders of the garrison work night and day to protect the citizens of Elwynn from the dangers beyond the forest."}
	,[94]	= {["title"] = "Fargodeep Mine"			,["x"] = 38.12	,["y"] = 83.71	,["lore"] = "The Fargodeep Mine is an abandoned gold mine located in Elwynn Forest, which has been overrun by kobolds.\n\nThe mine also functions as a barrier between the Stonefield Farm and Maclure Vineyards, two rival farms."}
	,[95]	= {["title"] = "Jerod's Landing"		,["x"] = 48.35	,["y"] = 87.64	,["lore"] = "Jerod's Landing is a boat landing on the Elwynn Forest bank of the Nazferiti River.\nThe landing has was taken over by the Defias Brotherhood, and they used it to smuggle stolen goods from Redridge to Klaven's Tower in Westfall.\n\nWith the fall of the Defias Brotherhood, they have subsquently lost control of this point and now the dock is operated independently by the Dockmaster."}
	,[96]	= {["title"] = "Tower of Azora"			,["x"] = 64.94	,["y"] = 69.96	,["lore"] = "The Tower of Azora is a small mage tower in eastern Elwynn Forest.\nThe tower is run by a number of servants of Azora, who all appear to be Gnomish, and who are in turn presided over by the Archmage of Azora, Theocritus.\nThe denizens of the tower are in a constant feud with the inhabitants of the Tower of Ilgalar in Redridge Mountains, ruled over by the evil sorcerer Morganth.\nThe two towers are constantly spying on one another through magical means.\n\nAn interview with the servants of Azora in the Gadgetzan Times reveals they are unable to wield magic and are somewhat resentful of the abilities of their master.\nIt also shows that many things straying too near the tower are adversely affected by its magical aura, so the servants often have to battle living buckets and mutant butterflies."}
	,[97]	= {["title"] = "Heroes' Vigil"			,["x"] = 74.45	,["y"] = 51.63	,["lore"] = "Heroes' Vigil is the central area of the Stone Cairn Lake island in eastern Elwynn Forest.\nIt features a ring of stones, and a monument called the Stone of Remembrance which commemorates the dead from the orcs' sacking of Goldshire and other nearby regions during the First War."}
	,[98]	= {["title"] = "Eastvale Logging Camp"	,["x"] = 80.9	,["y"] = 66.23	,["lore"] = "Eastvale Logging Camp is located in the far east of Elwynn Forest, under the very shadow of Redridge Mountains north of the main road.\nOrders for lumber are constantly streaming in from various buyers and the lumberjacks work against strict deadlines.\nBecause of its location in more hostile wilderness, wild animals are proving to be troublesome.\nWolves and bears in the area have become a menace, chasing off workers and threatening to cause delays in delivery deadlines.\nThe problem has become significant enough that the Stormwind Guard has become involved, recruiting adventurers to collect abandoned lumber and eradicate some of the aggressive wildlife."}
	,[99]	= {["title"] = "Thunder Falls"			,["x"] = 24.96	,["y"] = 58.2	,["lore"] = "Thunder Falls is a narrow ravine, located in the mountains of north-western Elwynn Forest.\nA steep path leading up to the ravine can be found on the right of Mirror Lake's waterfall where there is a small rural cottage overrun by Bandits.\nIf the river is followed it will eventually wind into another waterfall that empties near the border of Westfall.\nThe bottom of the waterfall can be reached from above by carefully navigating through the hilly terrain.\n\nThunder Falls is quite unusual in the sense that it is a ravine with double-sided waterfall ends.\nThe falls are fed by a third, inaccessible waterfall from the cliffs on the northern side of the mountains."}
	,[100]	= {["title"] = "Furlbrow's Pumpkin Farm"	,["x"] = 49.77	,["y"] = 19.81	,["lore"] = "Furlbrow's Pumpkin Farm (formerly known as Furlbrow's Pumpkin Patch) was one of the many farms in Westfall taken over by the Defias Brotherhood and their mechanical harvesters.\nThe killing machines used to patrol the fields before the Cataclysm, with the Defias taking up residence in the farm buildings.\nFarmer Furlbrow and his wife fled during that time to the road near the Jansen Stead in northern Westfall.\n\nAfter the events of the Cataclysm, the Furlbrows have apparently met an untimely demise near the Jansen Stead, their deaths currently under investigation.\nTheir farm was claimed by the Homeless Stormwind Citizens, Transients and similar individuals who can be found throughout the area."}
	,[101]	= {["title"] = "Raging Chasm"			,["x"] = 38.36	,["y"] = 42.65	,["scale"] = 2	,["lore"] = "The Raging Chasm is a sinkhole created by the Cataclysm.\nWhat exactly happened to cause it, is still unknown.\nBecause of the rocks and trees flying around what appears to be a pillar of air, one could assume it is caused by angry Air Elementals."}
	,[102] 	= {["title"] = "Westfall Lighthouse"	,["x"] = 30.43	,["y"] = 85.71	,["lore"] = "The Westfall Lighthouse sits just off the coast on the far southern edge of Westfall.\nThe friendly ghost of Captain Grayson roams around this small island."}
	,[103] 	= {["title"] = "Dagger Hills"			,["x"] = 44.82	,["y"] = 80.29	,["lore"] = "The Dagger Hills is actually a ridge, sitting behind Moonbrook in Westfall.\nThe area is mostly devoid of life, with Grimbooze Thunderbrew being the only exception.\n\nBefore the fall of the Defias Brotherhood, this area was the home of their strongest members."}
	,[104] 	= {["title"] = "Moonbrook"				,["x"] = 43.41	,["y"] = 69.47	,["scale"] = 2	,["lore"] = "Prior to the coming of the orcs to Azeroth, Moonbrook served as the focal point of the farmlands of Westfall.\nDuring the First War, Moonbrook and its sister town Goldshire were the final two towns to fall to the Horde prior to the razing of Stormwind Keep.\nIt was rebuilt following the Alliance victory in the Second War.\n\nOne prominent family from Moonbrook is the Cooper family, who lived in a residence in the western part of the town.\nThe nearby mine was overseen by Foreman Thistlenettle, a member of the Explorers' League.\n\nFollowing successful efforts by the Defias to seize control of Westfall, Moonbrook was abandoned.\nFor a while, it was controlled by the Defias and used by them to access their main base of operations, the Deadmines.\nSince the defeat of Edwin VanCleef and the fall of the Brotherhood, Moonbrook has become home to a large number of vagrants."}
	,[105] 	= {["title"] = "Mortwake's Tower"		,["x"] = 70.61	,["y"] = 74.64	,["lore"] = "Mortwake's Tower, formerly Klaven's Tower, named after its rogue Defias master Klaven Mortwake, lies at the southeastern edge of Westfall near the river.\n\nSI:7 was previously scouting this mage tower for some time and sometimes covertly sought help from adventurous rogues to sneak in and gather intelligence.\nIt was a well known launching point for Defias activity such that it has also been called the \"Defias Tower\".\nKlaven's Tower was being used, along with Jerod's Landing in Elwynn Forest, in the smuggling of stolen goods from Redridge."}
	,[106] 	= {["title"] = "Sentinel Hill"			,["x"] = 56.33	,["y"] = 47.51	,["lore"] = "Sentinel Hill has been recently reinforced with the return of Gryan Stoutmantle and the Westfall Brigade from the war in Northrend.\nThe King has sent supplies, troops, and tanks in hopes of rebuilding the former breadbasket of the kingdom and to house the citizens of Stormwind whose homes were destroyed.\nFrom Sentinel Hill, the Westfall Brigade has been able to reclaim much of the lands, such as Moonbrook, the Furlbrow's Pumpkin Farm, and The Jansen Stead.\nThe town isn't finished yet, and cannot let the homeless that surround the town in yet."}
	,[107] 	= {["title"] = "New Tinkertown"			,["x"] = 49.53	,["y"] = 45.43	,["scale"] = 0.5	,["lore"] = "Following the conclusion of Operation: Gnomeregan, High Tinker Mekkatorque and his people have gained a foothold just outside the city in New Tinkertown.\n\nResolute in reclaiming their lost capital, Gnomeregan's exiles have begun an assault against the traitorous Mekgineer Thermaplugg.\nTraveling from their temporary residence in Ironforge, they are led by the esteemed High Tinker Gelbin Mekkatorque, leader of the gnomes, and seek to restore Gnomeregan to its past glory."}
	,[108] 	= {["title"] = "Kharanos"				,["x"] = 53.49	,["y"] = 51.13	,["lore"] = "Kharanos is a bustling little town nestled among the mountain peaks of Dun Morogh. The town is surrounded by the stark wintry wilds of Dun Morogh, so adventure is a common commodity.\nKharanos is home to a large forge, a gnomish workshop, and the famous Thunderbrew Distillery, where adventurers can sit down and drink some of the best ale available in the world.\n\nFor all its quaint charm, Kharanos is a hub of military activity, defending against all manner of threats in the region.\nDirectly to the west is a large cavern inhabited by fierce Wendigo.\nTo the northwest, the Frostmane trolls have entrenched themselves at Shimmer Ridge.\n\nOnce, a giant frostame troll attacked the town and almost every dwarf.\nOnly Lazlo Grindwidget was able to defeat the troll thus he was honored as a hero of Kharanos.\n\nDuring one of the earthquakes preceding the Shattering, the Distillery was damaged and High Priest Rohan, Anduin Wrynn, and Aerin worked hard to help the injured and free the trapped.\nAfter clearing out the first floor an aftershock hit Kharanos, causing the remains of building to fall into a sinkhole.\nAerin, Anduin's friend and protector, was in the building when it fell into the earth and died with the others that were still inside.\nAnduin used all his strength to try to save her from underneath the rubble, his fingers were bloody and his strength diminished, crying for surrounding dwarves and draenei to help him, until he passed out from exhaustion.\nAfter the shattering, the Brewery ws rebuild."}
	,[109] 	= {["title"] = "Ironforge"				,["x"] = 60.38	,["y"] = 33.41	,["scale"] = 0.5	,["lore"] = "Ironforge is the capital city of the dwarves, a member of the Alliance.\nIt is the ancestral home of the Bronzebeard dwarves.\nThe Council of Three Hammers rules the kingdom of Khaz Modan from the throne room within the city.\n\nCarved into the stone heart of Khaz Modan, the mighty city of Ironforge is a testament to the dwarves’ strength and resilience.\nThe city is perhaps the most intricate of the Alliance cities, boasting many small passageways, shops built into the rock walls, and cavernous rooms.\nThe feel of the city is a bustling, rowdy, and somewhat industrial one.\nHowever, it is predominantly safe-feeling and cozy; fires roar in the hearths of the inns and shops, and much dwarven laughing and frivolity is to be heard.\nAlso, unlike Stormwind and Darnassus, the city is actually a massive cavern carved into the earth by the dwarves; the ceiling and floor are both hard stone.\n\nMainly because of the Deeprun Tram, linking Ironforge and Stormwind City, and the district of Tinker Town, Ironforge is one of the most racially diverse cities in the Alliance world.\nDwarves predominate, of course, but you will find plenty of gnomes even outside of Tinker Town, and probably as many humans.\nYou will find almost no night elves however, as they probably prefer more natural and open spaced environments.\nWith the Council of Three Hammers uniting all three dwarven clans, Ironforge has recently welcomed Dark Iron dwarves and Wildhammer dwarves into Ironforge as well."}
	,[110] 	= {["title"] = "Gol'Bolar Quarry"		,["x"] = 76.25	,["y"] = 53.40	,["scale"] = 0.5	,["lore"] = "Gol'Bolar Quarry was once a dwarven excavation site but, in the middle of a dig, the dwarves uncovered one of the underground caverns belonging to the troggs.\nThe troggs pushed the dwarves out, and also took over the quarry outside of the mine."}
	,[111] 	= {["title"] = "Helm's Bed Lake"		,["x"] = 83.98	,["y"] = 51.93	,["lore"] = "Helm's Bed Lake is a smallish lake in southeastern Dun Morogh.\nAlthough the lake has mostly frozen over, a hole in the ice is maintained at all times in order to provide access to fresh water.\nSince the Cataclysm, angry water elementals have taken control over the lake."}
	,[112] 	= {["title"] = "North Gate Outpost"		,["x"] = 91.12	,["y"] = 37.78	,["scale"] = 0.5	,["lore"] = "The mountaineers stationed at the outpost are busily defending it from encroaching wildlife, and some dwarves have gone missing in the mountains in search of the more ferocious beasts."}
	,[113] 	= {["title"] = "Ironforge Airfield"		,["x"] = 77.69	,["y"] = 22.94	,["scale"] = 1.5	,["lore"] = "The Ironforge Airfield is an airfield located in a high mountain valley northeast of the dwarven capital city of Ironforge.\nIt has two landing strips, and several gnome pilots are there standing next to their planes or tinkering with them.\nAround the airfield, there are a series of dwarven buildings and structures.\nMountaineers from Ironforge patrol the area, and some members of the Stormpike Guard can be found here too.\nNorth of the airfield there is a gryphon roost, but it only connects to Gol'Bolar Quarry via a Flying Machine."}
	,[114] 	= {["title"] = "Darnassus"				,["x"] = 38.59	,["y"] = 47.55	,["lore"] = "Darnassus is the capital city of the night elves of the Alliance.\nThe high priestess, Tyrande Whisperwind, resides in the Temple of the Moon, surrounded by other sisters of Elune and her mate, the Arch-Druid Malfurion Stormrage.\n\nIn the aftermath of the Third War, the night elves had to adjust to their mortal existence.\nSuch an adjustment was far from easy, and there were many night elves who could not adjust to the prospects of aging, disease and frailty.\nSeeking to regain their immortality, a number of wayward druids conspired to plant a special tree that would reestablish a link between their spirits and the eternal world.\nWith Malfurion Stormrage missing, Fandral Staghelm — the leader of those who wished to plant the new World Tree - became the new Arch-Druid.\nIn no time at all, he and his fellow druids had forged ahead and planted the great tree, Teldrassil, off the stormy coasts of northern Kalimdor.\nUnder their care, the tree sprouted up above the clouds.\nAmong the twilight boughs of the colossal tree, the wondrous city of Darnassus took root.\nDarnassus was built to honor the survival of the night elven race."}
	,[115] 	= {["title"] = "Wellspring Lake"		,["x"] = 44.37	,["y"] = 36.70	,["lore"] = "Wellspring Lake is a small lake northeast of Darnassus and southeast of The Oracle Glade in Teldrassil.\nFed by a natural spring deep within the land of the World Tree, this small lake is drained by the Wellspring River.\nPreviously a favored spot for night elven fishermen, the lake is now the home of corrupted timberlings."}
	,[116] 	= {["title"] = "Oracle Glade"			,["x"] = 39.16	,["y"] = 29.89	,["scale"] = 0.5	,["lore"] = "The Oracle Glade is a shrine in the northwestern area of Teldrassil.\nOne of the sacred moonwells lies there, as well as the magical Oracle Tree.\n\nThe Oracle Glade is the place where Malfurion Stormrage meditates."}
	,[117] 	= {["title"] = "Starbreeze Village"		,["x"] = 65.16	,["y"] = 50.93	,["lore"] = "Starbreeze Village lies south of Shadowglen and east of Dolanaar in Teldrassil.\nOnce a night elf village, Starbreeze is now overrun by corrupted furbolgs, an indication of the demonic infection that bleeds into Teldrassil."}
	,[118] 	= {["title"] = "Gnarlpine Hold"			,["x"] = 42.31	,["y"] = 69.34	,["lore"] = "Gnarlpine Hold was formally home to the Gnarlpine furbolgs.\nRecently, corruption has taken over the area and many demons are now present.\nA steady stream of demons flow out of the area to the north where Tarindrella and Teldrassil ancients meet for battle."}
	,[119] 	= {["title"] = "Rut'theran Village"		,["x"] = 55.48	,["y"] = 90.23	,["lore"] = "Rut'theran Village is an outpost port for the night elf city of Darnassus, located at the very bottom of the great tree Teldrassil.\nThere is a portal here that goes directly into Darnassus, as well as three docks with regular boats going to Exodar and Stormwind City.\n\nRut'theran Village originally had just one dock connected to Auberdine in Darkshore.\nDuring the Shattering, several parts of the village were destroyed and Auberdine was destroyed as well.\nSome of the services in Rut'theran Village were relocated to other parts of the now shattered island, and docks were added for the destinations previously reachable from Auberdine."}
	,[120] 	= {["title"] = "Exodar"					,["x"] = 37.00	,["y"] = 47.00	,["lore"] = "The Exodar is the enchanted capital city of the draenei who chose to depart from Draenor.\n\nAt some point before the present, the naaru arrived in the realm of Outland with a \"dimensional fortress\" known as Tempest Keep.\nThe naaru dispersed throughout the ravaged world, leaving the fortress defenseless.\nSeeing an opportunity to strike, Kael'thas Sunstrider and his many blood elf legions assaulted Tempest Keep and captured it, taking possession of its treasures and kidnapping the sole naaru occupant, M'uru, sending him back to Silvermoon City for the magisters to utilize in their thirst for magic.\n\nVelen, the courageous prophet who had led the draenei people since their exodus from Argus millennia before, had hid with the remainder of his people in the wake of the Legion-instigated orcish onslaught.\nWith the Broken Farseer Nobundo, first of the draenei shaman, at his side, the Prophet personally led a raid on Tempest Keep to wrest control of one of its satellite structures, the Exodar.\n\nThe draenei eventually took control of the Exodar and used it to escape Outland.\nThe blood elves, discovering what the draenei were planning, sabotaged the dimensional engines of the vessel.\nWhen the draenei activated it, the engine malfunctioned and sent the Exodar hurtling out of control through the Twisting Nether until it reached the closest habitable planet, Azeroth.\nThe crippled ship screamed across the skies of Northern Kalimdor, crystals flying everywhere, until it crash-landed on a small island chain off the coast of Darkshore.\nThe survivors took the islands as their new homeland, and set up their new capital in the largest intact portion of the still-smoking ship."}
	--,[110] 	= {["title"] = ""			,["x"] = 0	,["y"] = 0	,["lore"] = ""}
	--,[110] 	= {["title"] = ""			,["x"] = 0	,["y"] = 0	,["lore"] = ""}
	
	}
}